### ISSUE TITLE
Can we use this plugin to prevent overwriting a certain field?

### ISSUE THREAD

**Issue by arsaboo** [edgars-supe/beets-importreplace#4]
I have manually entered `genre` for my music and I would like to retain them. Wondering if it is possible to use this plugin to prevent overwriting certain fields, e.g., genre.

**Comment by edgars-supe** [comment]
Hi! This plugin replaces information in the incoming data from Musicbrainz, Spotify, etc. It does not impact what beets does with specific tags. That said, if you want to prevent beets from overwriting your `genre` tag data, perhaps you could use [this config flag](https://beets.readthedocs.io/en/stable/reference/config.html#genres), just don't specify an MB server.

Hmm, on second thought, if beets doesn't overwrite the `genre` field if it's empty in the metadata, perhaps making it empty would work. 
```yaml
    - item_fields: genre
      replace:
        '.*': ''
```

**Comment by arsaboo** [comment]
Good idea...making it empty may work. I will try it and confirm.

**Comment by arsaboo** [comment]
I tried it on the `albumartist` field and it worked. I will close this for now. Thanks!
