### ISSUE TITLE
Beets throwing error loading plugin importreplace

### ISSUE THREAD

**Issue by neilanthonystuckey** [edgars-supe/beets-importreplace#6]
I am running Windows 10 Pro Version 10.0.19045 Build 19045

Python error and version
** error loading plugin importreplace:
Traceback (most recent call last):
File "c:\users\neila\appdata\local\programs\python\python36\lib\site-packages\beets\plugins.py", line 268, in load_plugins
namespace = __import__(modname, None, None)
File "c:\users\neila\appdata\local\programs\python\python36\lib\site-packages\beetsplug\importreplace.py", line 3, in <module>
from re import Pattern
ImportError: cannot import name 'Pattern'

beets version:
beets in c:\users\neila\appdata\local\programs\python\python36\lib\site-packages (1.6.0)

beets config.yaml

plugins: importreplace fromfilename discogs chroma lidarrfields scrub
art_filename: folder
threaded: no
per_disc_numbering: yes
id3v23: yes
asciify_paths: true

match:
  strong_rec_thresh: 0.05
  max_rec:
    source: low
    artist: strong
    album: strong
    media: low
    mediums: low
    year: low
    country: low
    label: low
    catalognum: low
    albumdisambig: low
    album_id: low
    tracks: strong
    missing_tracks: low
    unmatched_tracks: low
    track_title: strong
    track_artist: strong
    track_index: low
    track_length: low
    track_id: low

paths:
    default: $lidarralbum ($year)/%if{$audiodisctotal,$disc - }${track}. $title
    singleton: $lidarralbum ($year)/%if{$audiodisctotal,$disc - }${track}. $title
    comp: $lidarralbum ($year)/%if{$audiodisctotal,$disc - }${track}. $title
    albumtype_soundtrack: $lidarralbum ($year)/%if{$audiodisctotal,$disc - }${track}. $title
        
import:
    write: yes
    copy: no
    move: yes
    resume: no
    incremental: no
    quiet_fallback: asis
    timid: no
    duplicate_action: keep
    log: C:\Users\neila\AppData\Roaming\beets\beets.log
    languages: ['en']
    group_albums: no
    
importreplace:
  replacements:
    - item_fields: title artist artist_sort artist_credit
      album_fields: album artist artist_sort artist_credit
      replace:
        '[\u2018-\u201B]': ''''
        '[\u201C-\u201F]': '"'
        '[\u2010-\u2015]': '-'

discogs:
    source_weight: 0.0

chroma:
    auto: yes

scrub:
    auto: yes

**Comment by edgars-supe** [comment]
Hi! 
While I could reproduce your issue (but not solve it), I think the best course of action would be to update to a newer version of Python. 3.6 has reached end-of-life and is no longer supported.
